name = "italian-learning-api"
main = "src/server.ts"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "italian-learning-db"
database_id = "5670e3a0-6b35-4fdd-9269-b941f075fd1f"

